version: '3.1'

services:
  database_pg:
    image: postgres
    container_name: database_pg
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spring-boot_prova-cast-app
    ports:
    - 5432:5432
    volumes:
    - ./pg-data:/var/lib/postgresql/
    mem_limit: 512m 

  database_redis:
    image: redis
    container_name: database_redis
    ports:
      - 6379:6379
    volumes:
      - ./.myredis/conf:/usr/local/etc/redis
    command: bash -c "redis-server"
    mem_limit: 256m 

  server_maven:
    image: maven
    container_name: server_maven
    environment:
      DB_URL: jdbc:postgresql://database_pg:5432/spring-boot_prova-cast-app
    ports:
    - 80:80
    links:
      - database_pg
    volumes:
    - ./:/usr/src/
    working_dir: /usr/src/
    command: bash -c "mvn spring-boot:run"
    mem_limit: 512m

  metrics_prometeus:
    image: prom/prometheus:latest
    container_name: metrics_prometeus
    ports:
      - 9090:9090
    volumes:
      - ./src/main/resources/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    mem_limit: 128m
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    mem_limit: 128m