server:
  port: 80

  error:
    include-stacktrace: on-param

spring:
  application:
    name: ProvaCast

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    username: postgres
    password: postgres
    url: ${DB_URL}
    # url: jdbc:postgresql://host.docker.internal:5432/spring-boot_prova-cast-app

  # redis:
  #   host: localhost
  #   port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
        # include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true

info:
  app: Prova Cast
  website: https://www.linkedin.com/in/ribaslucian/
  github: https://github.com/ribaslucian